#Customized YML

name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test navigation links
        run: |
          grep -q 'href="data-sources.html"' src/index.html
          grep -q 'href="collection-methods.html"' src/index.html
          grep -q 'href="analysis-methods.html"' src/index.html
          grep -q 'href="publication-venues.html"' src/index.html

      - name: Test headers
        run: |
          grep -q 'Mining Software Repositories Reference Website!' src/index.html
          grep -q 'Data Sources!' src/data-sources.html
          grep -q 'Collection Methods!' src/collection-methods.html
          grep -q 'Analysis Methods!' src/analysis-methods.html
          grep -q 'Publication Venues!' src/publication-venues.html

      - name: Test homepage links
        run: |
          grep -q 'href="index.html"' src/data-sources.html
          grep -q 'href="index.html"' src/collection-methods.html
          grep -q 'href="index.html"' src/analysis-methods.html
          grep -q 'href="index.html"' src/publication-venues.html
