#Customized YML

name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test navigation links
        run: |
          grep -q "href="data-sources.html"" index.html
          grep -q "href="collection-methods.html"" index.html
          grep -q "href="analysis-methods.html"" index.html
          grep -q "href=\"publication-venues.html"" index.html
